update imports in README examples
05nelsonm/component-encoding pull request #25
Opened 2022-07-17 13:48 UTC by aSemy

Hi, I copied the base64 example, but the import was incorrect. I had to change it. 

I've not checked if the base16 and base32 packages are correct!

```kotlin
import io.matthewnelson.component.encoding.base64.* // error - no package 'encoding'
import io.matthewnelson.component.base64.* // works!
```

2022-07-19 09:58 UTC, 05nelsonm approved these changes
Good catch, thanks! :heart:

2022-07-19 10:03 UTC, 05nelsonm commented
> I've not checked if the base16 and base32 packages are correct!

Perhaps I got ahead of myself seeing it was just the README :rofl: . Seems like the base64 package path is the only outlier here.

- base16: `package io.matthewnelson.component.encoding.base16`
- base32: `package io.matthewnelson.component.encoding.base32`
- base64: `package io.matthewnelson.component.base64`

2022-07-19 10:05 UTC, 05nelsonm requested changes
See: https://github.com/05nelsonm/component-encoding/pull/25#issuecomment-1188856608

2022-07-20 12:52 UTC, aSemy commented
I'm not sure if you were asking to fix the packages or the readme, so I've made some suggestions that you can apply if you wanted to revert the readme :)

2022-07-20 23:41 UTC, 05nelsonm approved these changes
:+1:

2022-07-20 23:41 UTC, merged